CREATE TABLE IF NOT EXISTS public.workouts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nivel TEXT NOT NULL,
    dia INTEGER NOT NULL,
    titulo TEXT NOT NULL,
    foco TEXT NOT NULL,
    aquecimento JSONB NOT NULL,
    principal JSONB NOT NULL
);

-- Limpar a tabela antes de popular para evitar dados duplicados
DELETE FROM public.workouts;

INSERT INTO public.workouts (nivel, dia, titulo, foco, aquecimento, principal) VALUES
-- INICIANTE (Dias 1 a 6)
('INICIANTE', 1, 'Adaptação Técnica I', 'Técnica e Hábito', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Barra Fixa: 5 a 8 repetições negativas (segura descida 5s)", "Flexão de Braço: 4 séries com mínimo de 8 reps", "Natação: 4x25m crawl leve para recuperação ativa"]'),
('INICIANTE', 2, 'Fortalecimento Base', 'Tônus de Inferiores', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Afundo: 3x12 cada perna", "Agachamento: Isometria 3x30s na parede", "Ponte: Elevação Pélvica 3x15"]'),
('INICIANTE', 3, 'Resistência Leve', 'Respiração e Cadência', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Corrida: 800m leve + 4 tiros de 100m com 30s descanso", "Abs Remador: 4x15"]'),
('INICIANTE', 4, 'Fortalecimento Superiores', 'Resistência Localizada', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Burpee (sem salto): 3x10", "Dead Bug: 3x20 alternados", "Remada Curvada com peso leve: 4x12"]'),
('INICIANTE', 5, 'Endurance Tática', 'Resistência Geral', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Corrida: 1.5km ritmo constante", "Flexão de Braço (com joelhos) 3x Máx", "Isometria na Barra: 3x Máximo tempo possível"]'),
('INICIANTE', 6, 'Core e Recuperação', 'Núcleo e Mobilidade', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Abs Remador (Teste): Máx em 1 minuto", "Prancha Tática: 3x 45s", "Stiff com peso corporal ou mochila leve: 4x15"]'),

-- INTERMEDIARIO (Dias 1 a 6)
('INTERMEDIARIO', 1, 'Volume e Cadência', 'Aumento Progressivo', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Barra Fixa: 3 séries de 6 reps com pausa 3s no meio da subida", "Flexão de Braço: 4x15 execução rápida", "Natação: 6x25m focado em braçada longa"]'),
('INTERMEDIARIO', 2, 'Explosão e Agilidade', 'Potência Inferior', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Agachamento com Salto: 4x15", "Afundo Reverso: 3x12", "Agilidade: Zigue-zague entre cones e Deslocamento Lateral (5 min)"]'),
('INTERMEDIARIO', 3, 'Resistência Extrema EMOM', 'Sobrevivência', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Circuito EMOM 12min (A cada minuto feche): 10 flexões, 15 abs e 150m corrida", "Recuperação ativa com caminhada leve 2min"]'),
('INTERMEDIARIO', 4, 'Fortalecimento Costas e Peito', 'Volume de Supino', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Supino / Flexão fechada: 4x12", "Remada Curvada (carga moderada): 4x15", "Dead Bug: 4x20"]'),
('INTERMEDIARIO', 5, 'Resistência de Ladeira', 'Cardio Intenso', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Barra Fixa: 4x Máx", "Burpee: 4x15 reps", "Corrida de Ladeira/Inclinação: 4 tiros de 30s subindo"]'),
('INTERMEDIARIO', 6, 'Simulado Tático Reduzido', 'Preparação Mental', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Simulado: Corrida 1.5km ritmo de prova", "Abs Remador: Máx em 1 minuto", "Flexão de Braço: Máx em 1 minuto"]'),

-- AVANCADO (Dias 1 a 6)
('AVANCADO', 1, 'Sobrecarga Militar', 'Força Extra e Tiros d''água', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Barra Fixa: 4x8 com carga extra (ou colete)", "Flexão Pliométrica (bater palmas): 4x12", "Natação: 8x25m tiro de velocidade"]'),
('AVANCADO', 2, 'Potência Pura Base', 'Pliometria Inferior', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Agachamento Búlgaro pesado: 4x10", "Afundo Pliométrico (com salto duplo): 4x12", "Potência Superior: Arremesso de Medicine Ball 3x15 (ou Supino explosivo)"]'),
('AVANCADO', 3, 'Tiros de 400m', 'Ritmo de Edital', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Corrida Tática: 5 tiros de 400m no ritmo alvo do edital (40s desc)", "Abs Remador acelerado: 4x40", "Burpee Militar Completo: 3x15"]'),
('AVANCADO', 4, 'Edital Superior', 'Máximo Desgaste', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Simulado de Flexão: 1 Minuto", "Burpee: 4x20 Completos", "Barra Fixa com pegada variada: 4x Máx"]'),
('AVANCADO', 5, 'Super Circuito da Morte', 'Intensidade Máxima', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Super Circuito (2 rounds): Tiro 100m, Max Flexões e Max Barras (sem pausa)", "Corrida: 2km contínuos no ritmo letal do TAF"]'),
('AVANCADO', 6, 'SIMULADO OFICIAL DE PROVA', 'Condições Exatas do Edital', '[{"fase": 1, "titulo": "Fase 1 (05:00): Trote Leve", "exercicios": ["Caminhada ou trote leve constante."]}, {"fase": 2, "titulo": "Fase 2 (05:00): Loop de Mobilidade", "exercicios": ["Repita em loop o máximo possível até zerar o cronômetro:", "10 rotações de cada articulação.", "10 agachamentos.", "10 polichinelos.", "10 rotações de tronco."]}]', '["Realize a prova completa do seu Edital TAF sem intervalos extras", "Foque na contagem cronometrada com um fiscal", "Recuperação: Crioterapia (banho gelado e pernas pro alto) e hiper-hidratação"]');
